# matplotlib configurations
layout_params = dict(
    w_pad=1 / 24,
    h_pad=1 / 24,
    wspace=1e-2,
    hspace=1e-2,
)
poster_layout_params = dict(
    w_pad=1 / 48,
    h_pad=1 / 48,
    wspace=1e-2,
    hspace=1e-2,
)
mpl_params = {
    # "backend": "cairo",
    # lines
    "lines.linewidth": 0.5,
    "lines.markeredgecolor": "none",
    "lines.markeredgewidth": 0.0,
    # patches
    "patch.linewidth": 0.5,
    # font
    "font.family": "sans-serif",
    "font.sans-serif": ["Helvetica", "Liberation Sans", "DejaVu Sans"],
    "font.size": 6.0,
    # text
    "mathtext.fontset": "dejavuserif",
    "mathtext.default": "regular",
    # axes
    "axes.linewidth": 0.5,
    "axes.titlesize": 7.5,
    "axes.titleweight": "normal",
    "axes.titlepad": 4.0,
    "axes.labelsize": 7.5,
    "axes.labelpad": 2.0,
    "axes.labelweight": "normal",
    "axes.axisbelow": True,
    "axes.xmargin": 2.5e-2,
    "axes.ymargin": 2.5e-2,
    # ticks
    "xtick.major.size": 2.0,
    "xtick.major.width": 0.5,
    "xtick.major.pad": 2.0,
    "xtick.labelsize": 6.0,
    "ytick.major.size": 2.0,
    "ytick.major.width": 0.5,
    "ytick.major.pad": 2.0,
    "ytick.labelsize": 6.0,
    # grids
    "grid.color": "#ababab",
    "grid.linewidth": 0.5,
    # legend
    "legend.edgecolor": "#ababab",
    "legend.markerscale": 0.5,
    "legend.fontsize": 6.0,
    "legend.title_fontsize": 6.0,
    "legend.borderpad": 1 / 3,
    "legend.handlelength": 1.0,
    "legend.handleheight": 0.5,
    "legend.handletextpad": 0.5,
    "legend.columnspacing": 1.5,
    # figure
    "figure.titlesize": 9.0,
    "figure.titleweight": "bold",
    "figure.labelsize": 7.5,
    "figure.labelweight": "normal",
    "figure.figsize": (1.75, 1.75),
    "figure.subplot.left": 0.05,
    "figure.subplot.right": 0.95,
    "figure.subplot.bottom": 0.05,
    "figure.subplot.top": 0.95,
    "figure.subplot.wspace": 1e-2,
    "figure.subplot.hspace": 1e-2,
    "figure.constrained_layout.use": True,
    "figure.constrained_layout.h_pad": 1 / 24,
    "figure.constrained_layout.w_pad": 1 / 24,
    "figure.constrained_layout.hspace": 1e-2,
    "figure.constrained_layout.wspace": 1e-2,
    # scatter
    "scatter.edgecolors": "none",
    # saving
    "savefig.bbox": "tight",
    "savefig.pad_inches": 1 / 18,
    "savefig.transparent": True,
    "ps.fonttype": 42,
    "ps.useafm": False,
    "pdf.fonttype": 42,
    "pdf.use14corefonts": False,
    "pdf.inheritcolor": False,
}
sns_params = {
    "axes.facecolor": "white",
    "axes.edgecolor": "black",
    "axes.grid": True,
    "axes.axisbelow": True,
    "axes.labelcolor": "black",
    "figure.facecolor": "white",
    "grid.color": "#ababab",
    "grid.linestyle": "-",
    "text.color": "black",
    "xtick.color": "black",
    "ytick.color": "black",
    "xtick.direction": "out",
    "ytick.direction": "out",
    "patch.edgecolor": "black",
    "patch.force_edgecolor": False,
    "image.cmap": "viridis",
    "xtick.bottom": True,
    "xtick.top": False,
    "ytick.left": True,
    "ytick.right": False,
    "axes.spines.left": True,
    "axes.spines.bottom": True,
    "axes.spines.right": True,
    "axes.spines.top": True,
}
mpl_poster_params = {
    # "backend": "cairo",
    "font.family": "sans-serif",
    "font.sans-serif": ["DejaVu Sans"],
    "font.stretch": "condensed",
    "font.size": 18.0,
    "axes.titlesize": 18.0,
    "axes.titleweight": "regular",
    "axes.titlepad": 7.5,
    "axes.labelsize": 18.0,
    "axes.labelpad": 4.5,
    "axes.linewidth": 2.0,
    "axes.axisbelow": True,
    "xtick.labelsize": 16.0,
    "xtick.major.pad": 2.0,
    "xtick.minor.pad": 2.0,
    "xtick.major.size": 4.0,
    "xtick.minor.size": 4.0,
    "xtick.major.width": 1.25,
    "xtick.minor.width": 1.25,
    "ytick.labelsize": 16.0,
    "ytick.major.pad": 2.0,
    "ytick.minor.pad": 2.0,
    "ytick.major.size": 4.0,
    "ytick.minor.size": 4.0,
    "ytick.major.width": 1.25,
    "ytick.minor.width": 1.25,
    "figure.figsize": (3.84, 3.84),
    "figure.titlesize": 24.0,
    "figure.titleweight": "bold",
    "figure.labelsize": 20.0,
    "figure.constrained_layout.use": True,
    "figure.dpi": 60,
    "patch.linewidth": 2.0,
    "grid.linewidth": 1.25,
    "lines.linewidth": 2.0,
    "legend.fontsize": 16.0,
    "legend.title_fontsize": 16.0,
    "mathtext.default": "regular",
    "savefig.dpi": 400,
    "savefig.bbox": "tight",
    "savefig.transparent": True,
    "savefig.pad_inches": 0.1,
    "pdf.fonttype": 42,
    "pdf.use14corefonts": False,
    "pdf.inheritcolor": False,
    "ps.fonttype": 42,
    "ps.useafm": False,
}
